# EditorConfig helps developers define and maintain consistent coding styles

root = true

# Default for all files
[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true

# TOML (config files like config.toml, params.toml, netlify.toml)
[*.toml]
indent_style = space
indent_size = 2

# Markdown (disable trimming whitespace to preserve alignment)
[*.md]
trim_trailing_whitespace = false

# YAML (e.g. Netlify headers, GitHub workflows)
[*.yml]
indent_style = space
indent_size = 2

[*.yaml]
indent_style = space
indent_size = 2

# JSON
[*.json]
indent_style = space
indent_size = 2

# HTML
[*.html]
indent_style = space
indent_size = 2

# JavaScript / TypeScript
[*.{js,ts,jsx,tsx}]
indent_style = space
indent_size = 2

# CSS / SCSS
[*.{css,scss}]
indent_style = space
indent_size = 2

# Shell scripts
[*.sh]
indent_style = space
indent_size = 2
