[build]
command = "npm run build"
publish = "dist"


[build.environment]
NODE_VERSION = "25.7.0"
GO_VERSION = "1.26.0"
HUGO_VERSION = "0.155.3"
MISE_QUIET = "1"

[context.deploy-preview]
command = "npm run build:preview"

[context.production.environment]
HUGO_ENV = "production"
