[build]
command = "npm run build"
publish = "dist"


[build.environment]
NODE_VERSION = "22.18.0"
GO_VERSION = "1.24.6"
HUGO_VERSION = "0.148.2"
MISE_QUIET = "1"

[context.deploy-preview]
command = "npm run build:preview"

[context.production.environment]
HUGO_ENV = "production"
