# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
baseURL = "https://robb.sh"
defaultContentLanguage = "en"
description = "./robb.sh"
Copyright = "© 2024 Robb Romans · [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 0
ignoreFiles = ["^/_vendor/"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[permalinks]
posts = "/posts/:slug/"

[taxonomies]
tag = "tags"
# Categories are disabled by default.

# images = [""]
# themeColor = "#494f5c"
