colorScheme = "avocado"
defaultAppearance = "dark"
autoSwitchAppearance = true
#defaultThemeColor = "#494f5c" # Hermit
enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

robots = '''
User-agent: *
Allow: /
Sitemap: https://robb.sh/sitemap.xml
'''
fingerprintAlgorithm = "sha256"

[header]
layout = "basic" # valid options: basic, hamburger, hybrid, custom
# logo = "img/logo.jpg"
# logoDark = "img/dark-logo.jpg"
showTitle = true

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile" # valid options: page, profile, custom
showRecent = true
recentLimit = 5

[article]
[author]
name = "Robb Romans"
showDate = true
showDateUpdated = false
showAuthor = false
showBreadcrumbs = false
showDraftLabel = true
showEdit = true
editURL = "https://github.com/robb-romans/robb-sh-hugo/"
editAppendPath = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = false
showTaxonomies = false
showWordCount = true
showComments = true
# sharingLinks = ["facebook", "x-twitter", "mastodon", "pinterest", "reddit", "linkedin", "email", "threads", "telegram", "line", "weibo"]

[list]
showBreadcrumbs = false
showSummary = false
showTableOfContents = false
showTaxonomies = false
groupByYear = true
paginationWidth = 1

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
